baseURL = "https://vanguo.tech"
title = "vanguoo"
theme = "echo"
# languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
# è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å«ä¸­æ–‡/æ—¥æ–‡/éŸ©æ–‡ï¼Œè¯¥å‚æ•°ä¼šå½±å“æ‘˜è¦å’Œå­—æ•°ç»Ÿè®¡åŠŸèƒ½ï¼Œå»ºè®®è®¾ç½®ä¸ºtrue
hasCJKLanguage = true
# è®¾ç½®é¡µé¢ç”Ÿæˆå½¢å¼ï¼Œå°†é»˜è®¤çš„ç½‘ç«™è·¯å¾„/ä¿®æ”¹æˆ.html
uglyURLs = true

# paginate = 20
# pygmentsStyle = "bw"
# pygmentsCodeFences = true
# pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[markup.highlight]
codeFences=true
guessSyntax=true
hl_Lines = ""
# lineNoStart = 1
# lineNos = true
# lineNumbersInTable = true
noClasses = true
style = "github-dark"
tabWidth = 4

[permalinks]
posts = "/:filename"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[services.rss]
limit = 20

[author]
name = "vanguoo"
avatar = "https://pb.vanguo.tech/api/files/ge0cpwgmab5vb9s/501napnph9033bj/3_eca63_ad_4247_4390_b9_f2_bf150_acd4717_0KyIxr5aRw.jpeg"
bio = "æ…¢"
homepage = "https://vanguo.tech/"

# https://avatars.githubusercontent.com/u/55241884?s=400&u=0012781cbff266f14a595637441833f7ebb16664&v=4
[params]
favicon = "https://pb.vanguo.tech/api/files/ge0cpwgmab5vb9s/se308frxxi8n2vr/20230105192004_CPKf0IWkb7.jpg"
keywords = "Hugo, theme, echo"
description = "Hugo theme echo example site."
toc = true
navItems = [
  ["é¦–é¡µ", "/"],
  ["å½’æ¡£", "/posts.html"],
  ["å‹æƒ…é“¾æ¥", "/self.html"],
  ["å…³äºæˆ‘", "/about.html"],
]
# rss å…¨æ–‡è¾“å‡º
rssFullContent = true
uglyURLs = true
busuanzi = true # æ˜¯å¦ä½¿ç”¨ä¸è’œå­ç»Ÿè®¡ç«™ç‚¹è®¿é—®é‡
staticCDNPrefix = "https://cdn.bootcss.com/font-awesome/5.11.2"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
# profileAds = '<div class="p-4 mt-2 lg:mt-4 rounded shadow bg-white dark:bg-gray-800"><img class=" object-cover w-auto mx-auto mt-6" loading="lazy" src="" title="" alt=""></div>'
notFoundAds = ''


# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[social]
github = "vanguoo"
twitter = "vanguoo"
telegram = "vanguoo"
rss = "/atom.xml"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"


# [taxonomies]
# category = "categories"
# series = "series"
# tag = "tags"
# author = "authors"

# [[params.social]]
# name = "Github"
# icon = "fa fa-2x fa-github"
# weight = 1
# url = "https://github.com/vanguo996/"

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-2x fa-twitter"
# weight = 2
# url = "https://twitter.com/vanguo1/"


# [languages.zh-cn]
#     languagename = "Chinese"
#     title = "Code as Life!ğŸ™‚"

#     [languages.zh-cn.menu]
#         [[languages.zh-cn.menu.main]]
#             name = "å…³äº"
#             weight = 1
#             url = "/about/"
#         [[languages.zh-cn.menu.main]]
#             name = "å­¦ä¹ "
#             weight = 2
#             url  = "/self/"
#         [[languages.zh-cn.menu.main]]
#             name = "æŠ€æœ¯"
#             weight = 3
#             url  = "/dev/"
#         # [[languages.zh-cn.menu.main]]
#         #     name = "æŠ•èµ„"
#         #     weight = 4
#         #     url  = "/money/"
#         [[languages.zh-cn.menu.main]]
#             name = "ä¸ªäººé¡¹ç›®"
#             weight = 4
#             url  = "/project/"
#         [[languages.zh-cn.menu.main]]
#             name = "é•¿æœŸç›®æ ‡"
#             weight = 5
#             url  = "/goal/"
